# Generated by Django 4.1 on 2024-09-03 21:03

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Squad = apps.get_model('accounts', 'Squad')
    SteamProfile = apps.get_model('accounts', 'SteamProfile')
    SquadMembership = apps.get_model('accounts', 'SquadMembership')
    for squad in Squad.objects.using(schema_editor.connection.alias).all():
        for player in SteamProfile.objects.using(schema_editor.connection.alias).filter(squad = squad):
            SquadMembership.objects.using(schema_editor.connection.alias).create(squad = squad, player = player)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_squad_last_changelog_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=None, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads',
                                             to='accounts.steamprofile', verbose_name='Match')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members',
                                            to='accounts.squad', verbose_name='Player')),
            ],
        ),
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='squad',
            name='members',
        ),
    ]
