# Generated by Django 4.1 on 2024-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_squad_members_squadmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadmembership',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='squadmembership',
            name='trends',
            field=models.JSONField(default=dict),
        ),
    ]
