# Generated by Django 4.1.13 on 2024-09-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_squadmembership_stats_squadmembership_trends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadmembership',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='squadmembership',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='squadmembership',
            name='trends',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
