# Generated by Django 4.1.13 on 2025-04-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_squadmembership_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing', to='accounts.steamprofile'),
        ),
    ]
