# Generated by Django 4.1 on 2024-07-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_matchparticipation_new_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchparticipation',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='blind_time',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='fb_enemies',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='fb_teammates',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='fb_thrown',
        ),
        migrations.RemoveField(
            model_name='matchparticipation',
            name='util_dmg',
        ),
    ]
