# Generated by Django 4.1 on 2024-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_killevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipation',
            name='hltv',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='kast',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
