# Generated by Django 4.1 on 2024-07-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_remove_matchparticipation_kast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchparticipation',
            name='hltv',
        ),
    ]
