# Generated by Django 4.1 on 2024-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_remove_matchparticipation_hltv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchparticipation',
            options={'ordering': ['-adr']},
        ),
    ]
