# Generated by Django 4.1 on 2024-08-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_update_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchbadgetype',
            name='is_minor',
        ),
    ]
