# Generated by Django 4.1.13 on 2024-09-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_remove_matchbadgetype_is_minor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchparticipation',
            name='unique_pmatch_team_position',
        ),
    ]
