# Generated by Django 4.1.13 on 2024-09-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_remove_matchparticipation_unique_pmatch_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchparticipation',
            name='position',
        ),
    ]
