# Generated by Django 4.1.13 on 2024-09-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_remove_matchparticipation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchbadge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='stats.matchbadgetype'),
        ),
    ]
