# Generated by Django 4.1.13 on 2024-09-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_rename_scheduled_timestamp_updatetask_scheduling_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatetask',
            old_name='completed_timestamp',
            new_name='completion_timestamp',
        ),
    ]
