# Generated by Django 4.1.13 on 2025-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_rename_completed_timestamp_updatetask_completion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mtype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='new_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchparticipation',
            name='old_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
