# Generated by Django 4.1.13 on 2025-04-02 16:40

from django.db import migrations, models


def forwards(apps, schema_editor):
    MatchBadgeType = apps.get_model('stats', 'MatchBadgeType')
    MatchBadgeType.objects.using(schema_editor.connection.alias).bulk_create(
        [
            MatchBadgeType(pk='weapon-knife', name='Knife Kill'),
        ]
    )


def backwards(apps, schema_editor):
    MatchBadgeType = apps.get_model('stats', 'MatchBadgeType')
    MatchBadgeType.objects.using(schema_editor.connection.alias).filter(pk='weapon-knife').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_alter_match_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='killevent',
            name='weapon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(forwards, backwards),
    ]
