# Generated by Django 4.1.13 on 2025-04-07 08:41

from django.db import migrations, models


def forwards(apps, schema_editor):
    MatchParticipation = apps.get_model('stats', 'MatchParticipation')
    for mp in MatchParticipation.objects.using(schema_editor.connection.alias).all():
        if mp.old_rank == 0:
            mp.old_rank = None
        if mp.new_rank == 0:
            mp.new_rank = None
        mp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_killevent_weapon'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AddConstraint(
            model_name='matchparticipation',
            constraint=models.CheckConstraint(check=models.Q(('old_rank', 0), _negated=True), name='old_rank_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipation',
            constraint=models.CheckConstraint(check=models.Q(('new_rank', 0), _negated=True), name='new_rank_not_zero'),
        ),
    ]
