# Generated by Django 4.1.13 on 2025-04-09 14:54

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    MatchParticipation = apps.get_model('stats', 'MatchParticipation')
    for mp in MatchParticipation.objects.using(schema_editor.connection.alias).all():
        mp.executing_player = mp.player
        mp.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_squadmembership_position_and_more'),
        ('stats', '0024_matchparticipation_old_rank_not_zero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipation',
            name='executing_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_matchparticipations', to='accounts.steamprofile', verbose_name='Executing Player'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
