# Generated by Django 4.1.13 on 2025-04-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_squadmembership_position_and_more'),
        ('stats', '0026_alter_matchparticipation_executing_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipation',
            name='executing_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_matchparticipation', to='accounts.steamprofile', verbose_name='Executing Player'),
        ),
    ]
