# Generated by Django 4.1.13 on 2025-06-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_alter_matchparticipation_executing_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killevent',
            name='killer_x',
        ),
        migrations.RemoveField(
            model_name='killevent',
            name='killer_y',
        ),
        migrations.RemoveField(
            model_name='killevent',
            name='killer_z',
        ),
        migrations.RemoveField(
            model_name='killevent',
            name='victim_x',
        ),
        migrations.RemoveField(
            model_name='killevent',
            name='victim_y',
        ),
        migrations.RemoveField(
            model_name='killevent',
            name='victim_z',
        ),
    ]
